export { NotFound } from "pages/notFound/NotFound"
export { LandingPage } from "pages/landingPage/LandingPage"
export { LikedPage } from "pages/likedPage/LikedPage"
export { HistoryPage } from "pages/historyPage/HistoryPage"
export { WatchLaterPage } from "pages/watchLaterPage/WatchLater"
export { PlayListPage } from "pages/playListPage/PlayListPage"
export { VideoPage } from "pages/videoPage/VideoPage"
export { AuthorizationPage } from "pages/authorizationPage/AuthorizationPage"
export { RestrictAuth } from "pages/restrictAuth/RestrictAuth"
export { IndividualPlayListPage } from "pages/individualPlayListPage/IndividualPlayListPage"

